// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CancelExecution() {
  return window['go']['main']['App']['CancelExecution']();
}

export function CompleteCurrent(arg1) {
  return window['go']['main']['App']['CompleteCurrent'](arg1);
}

export function GetState() {
  return window['go']['main']['App']['GetState']();
}

export function Initialize(arg1) {
  return window['go']['main']['App']['Initialize'](arg1);
}

export function Navigate(arg1) {
  return window['go']['main']['App']['Navigate'](arg1);
}

export function RestartSession() {
  return window['go']['main']['App']['RestartSession']();
}

export function RunCode(arg1) {
  return window['go']['main']['App']['RunCode'](arg1);
}

export function SaveDraft(arg1, arg2) {
  return window['go']['main']['App']['SaveDraft'](arg1, arg2);
}

export function SetLanguage(arg1) {
  return window['go']['main']['App']['SetLanguage'](arg1);
}

export function SkipCurrent(arg1) {
  return window['go']['main']['App']['SkipCurrent'](arg1);
}

export function ValidateCode(arg1) {
  return window['go']['main']['App']['ValidateCode'](arg1);
}
