// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';
import {execution} from '../models';

export function CancelExecution():Promise<boolean>;

export function CompleteCurrent(arg1:string):Promise<main.StateView>;

export function GetState():Promise<main.StateView>;

export function Initialize(arg1:string):Promise<main.StateView>;

export function Navigate(arg1:number):Promise<main.StateView>;

export function RestartSession():Promise<main.StateView>;

export function RunCode(arg1:string):Promise<execution.Result>;

export function SaveDraft(arg1:string,arg2:string):Promise<void>;

export function SetLanguage(arg1:string):Promise<main.StateView>;

export function SetTrack(arg1:string):Promise<main.StateView>;

export function SkipCurrent(arg1:string):Promise<main.StateView>;

export function ValidateCode(arg1:string):Promise<execution.Result>;
